coaching/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('management.urls')),
    path('authentication', include('login.urls')),
    path('signup', include('signup.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from . import views

app_name = "login"

urlpatterns = [
    path("",views.index, name = 'index'),
    path("login", views.login_view, name = 'login'),
    path("logout", views.logout_view, name = 'logout')
]

management/urls.py
from django.urls import path
from . import views


app_name = 'management'
urlpatterns = [
    path("", views.home, name = 'home'),
    path("add_course", views.add_course, name = 'add_course'),
    path("save_course", views.save_course, name = 'save_course'),
    path("add_student", views.add_student, name = 'add_student'),
    path("save_student", views.save_student, name = 'save_student'),
    path("assign_course", views.assign_course, name = 'assign_course'),
    path("save_to_course", views.save_to_course, name = 'save_to_course'),
    path("add_teacher", views.add_teacher, name = 'add_teacher'),
    path("save_teacher", views.save_teacher, name = 'save_teacher'),
    path("teachers", views.list_teachers, name = 'list_teachers'),
    path("upload_pic", views.upload_pic, name = 'upload_pic'),
    path("departments/", views.departments, name = 'departments'),
    path("departments/<str:department>", views.courses, name = 'courses'),
    path("departments/<str:department>/<str:course>", views.course_details, name = 'course_details')
]

signup/urls.py
from django.urls import path
from . import views

app_name = 'signup'

urlpatterns = [
    path("", views.signup ,name = 'signup'),
    path("signin", views.signin, name = 'signin'),
]

login/models.py
from django.db import models

# Create your models here.

login/views.py
from django.shortcuts import render
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login:login'))
    else:
        return HttpResponseRedirect(reverse('management:home'))
def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username = username, password = password)
        if user:
            login(request,user)
            for key, value in request.session.items():
                print(key,value)
            print(request.session['_auth_user_id'])
            print(request.user)
            print(request.user.id)
            if 'next' in request.POST:
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('management:home'))
        else:
            return render(request, 'login/login.html')

    return render(request, "login/login.html")

def logout_view(request):
    logout(request)
    return render(request, "login/login.html")

login/templates/login/index.html
{% extends "login/layout.html" %}
{% load static %}

{% block title %}
    loggedin
{% endblock %}
    
{% block body %}
<h1>welcome {{request.user.id}}</h1>
<a href="{% url 'login:logout' %}">Logout {{request.user|title}}</a>
{% endblock %}

login/templates/login/layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'login/styles.css' %}">
        <title>
            {% block title %}
            {% endblock %}
        </title>
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Pathway+Gothic+One&display=swap" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar sticky-top navbar-expand-lg navbar-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'management:home' %}">
                <img src="{% static 'management/logo.png' %}" width="30" height="30" alt=""> 
              </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            </div>
          </nav>
        <div class="container mt-3">  
          {% block body %}
          {% endblock %}
        </div>
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

login/templates/login/login.html
{% extends "login/layout.html" %}
{% load static %}

{% block title %}
login
{% endblock %}
{% block body %}
<h3 class="text-center">Login</h3>
<div class="row">
    <div class="col-lg-3">
    </div>
    <div class="col-lg-6 border rounded border-success p-3" style="background-color:#05F1B8;">

        <form action="{% url 'login:login' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" id="username" name="username" class="form-control">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" id="password" class="form-control">
            </div>
            <small>New User? <a href="{% url 'signup:signup' %}">SignUp!</a></small>
            <br>
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{request.GET.next}}">
            {% endif %}
            <br>
            <button class="btn btn-sm btn-success" type="submit"> Login </button>
        </form>
    </div>
    <div class="col-lg-3">

    </div>
</div>
{% endblock %}