coaching/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('management.urls')),
    path('authentication', include('login.urls')),
    path('signup', include('signup.urls'))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from . import views

app_name = "login"

urlpatterns = [
    path("",views.index, name = 'index'),
    path("login", views.login_view, name = 'login'),
    path("logout", views.logout_view, name = 'logout')
]

management/urls.py
from django.urls import path
from . import views


app_name = 'management'
urlpatterns = [
    path("", views.home, name = 'home'),
    path("add_course", views.add_course, name = 'add_course'),
    path("save_course", views.save_course, name = 'save_course'),
    path("add_student", views.add_student, name = 'add_student'),
    path("save_student", views.save_student, name = 'save_student'),
    path("assign_course", views.assign_course, name = 'assign_course'),
    path("save_to_course", views.save_to_course, name = 'save_to_course'),
    path("add_teacher", views.add_teacher, name = 'add_teacher'),
    path("save_teacher", views.save_teacher, name = 'save_teacher'),
    path("teachers", views.list_teachers, name = 'list_teachers'),
    path("upload_pic", views.upload_pic, name = 'upload_pic'),
    path("departments/", views.departments, name = 'departments'),
    path("departments/<str:department>", views.courses, name = 'courses'),
    path("departments/<str:department>/<str:course>", views.course_details, name = 'course_details')
]

management/models.py
from django.db import models

# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.name}"

class Course(models.Model):
    name = models.CharField(max_length=50)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='its_courses')
    no_of_students = models.IntegerField(default=0)

    def increase_student(self):
        self.no_of_students +=1

    def check_capacity(self):
        if self.no_of_students < 10:
            return True
        else:
            return False
    def capacity(self):
        return self.no_of_students

    def __str__(self):
        return f"{self.name}"

class Student(models.Model):
    name = models.CharField(max_length=50)
    gender = models.CharField(max_length=11)
    courses = models.ManyToManyField(Course,related_name = 'its_students',blank=True)

    def __str__(self):
        return f"{self.name}"

class Teacher(models.Model):
    name = models.CharField(max_length=100)
    department = models.ForeignKey(Department, on_delete=models.PROTECT, related_name='its_teachers')
    gender = models.CharField(max_length=11)
    age = models.IntegerField()
    pro_pic = models.ImageField(blank = True, null = True, upload_to = "profile_pictures/")
    head = models.ForeignKey(Department,on_delete=models.PROTECT, related_name = "department_head", null=True,blank=True)

    def __str__(self):
        return f"{self.name}"

management/forms.py
from django.shortcuts import render
from django import forms
from .models import Department,Student,Course
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse

choices = []
departments = Department.objects.all()
for department in departments:
    s = (department.id, department.name)
    choices.append(s)


class Course_form(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs= {'class': 'form-control form-control-sm'}),max_length=50, label='Name')
    department = forms.ChoiceField(widget=forms.Select(attrs= {'class': 'form-select form-select-sm'}), choices=choices,label='Choose department')

genders = [("male", "Male"),("female","Female"),("transgender", "Transgender")]



class Student_form(forms.Form):
    name = forms.CharField(max_length=50, label='Students Name', widget= forms.TextInput(attrs={"class":"form-control form-control-sm"}))
    gender = forms.ChoiceField(choices=genders, label="Gender", widget=forms.RadioSelect)

class Teacher_form(forms.Form):
    first_name = forms.CharField(max_length=50, label= 'First Name', widget=forms.TextInput(attrs={"class":"form-control form-control-sm"}))
    last_name = forms.CharField(max_length=50, label= 'Last Name', widget=forms.TextInput(attrs={"class":"form-control form-control-sm"}))
    department = forms.ChoiceField(widget=forms.Select(attrs={"class":"form-select form-select-sm"}), choices=choices, label= 'Choose Department')
    gender = forms.ChoiceField(widget=forms.RadioSelect, choices=genders, label= 'Gender')
    age = forms.IntegerField(widget=forms.NumberInput(attrs={"class":"form-control form-control-sm"}), label= 'Age', min_value= 0, max_value=60)
    pro_pic = forms.ImageField(required=False,label="Profile Picture")
    head = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,choices=choices,label= 'Department Head of', required=False)

class Upload_form(forms.Form):
    pro_pic = forms.ImageField(label="Upload Image: ", required=False)

management/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import login,logout,authenticate
from .models import Department,Course,Student,Teacher
from .forms import Course_form,Student_form,Teacher_form,Upload_form
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist,EmptyResultSet
from django.contrib.auth.decorators import login_required

# Create your views here.

def home(request):
    return render(request, "management/home.html")

@login_required(login_url='login:login')
def add_course(request):
    choices = []
    try:
        departments = Department.objects.all()
    except Department.DoesNotExist:
        return HttpResponseRedirect(reverse('management:departments'))
    for department in departments:
        s = (department.id, department.name)
        choices.append(s)

    return render(request, "management/index.html",{
            "form":Course_form()
        })

def save_course(request):
    if request.method == "POST":
        form = Course_form(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name'].capitalize()
            dep_id = int(form.cleaned_data['department'])
            department = Department.objects.get(pk = dep_id)
            try:
                check_course = Course.objects.get(name=name)
            except:
                course = Course(name = name, department=department)
                course.save()
                return render(request, "management/index.html",{
                    "form": Course_form(),
                    "message": f"{name} course added to {department} department"
                })
            else:
                return render(request, "management/index.html",{
                    "form":form,
                    "message": f"{name} course already exists!"
                })
        else:
            return HttpResponseRedirect(reverse('management:add_course'))
    else:
        return HttpResponseRedirect(reverse('management:add_course'))

@login_required(login_url='login:login')
def add_student(request):
    return render(request, "management/add_student.html", {
        "form":Student_form()
    })
    
def save_student(request):
    if request.method == "POST":
        form = Student_form(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name'].capitalize()
            gender = form.cleaned_data['gender']
            try:
                check_student = Student.objects.get(name=name)
            except Student.DoesNotExist:
                student = Student(name=name,gender=gender)
                student.save()
                return render(request, "management/add_student.html",{
                    "form":Student_form(),
                    "message":"New Student Registered"
                })
            else:
                return render(request, "management/add_student.html",{
                    "form":form,
                    "message":"Student already registered!"
                })
        else:
            return render(request, "management/add_student.html", {
                "form":form,
                "message":"Invalid form! Please fill up the information again."
            })
    else:
        return HttpResponseRedirect(reverse('management:add_student'))

@login_required(login_url='login:login')
def assign_course(request):
    try:
        courses = Course.objects.all()
        students = Student.objects.all()
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('management:index'))
    return render(request, "management/assign_course.html", {
        "courses":courses,
        "students":students
    })
def save_to_course(request):
    if request.method == 'POST':
        c = request.POST["course"]
        s = request.POST["student"]
        print(c,s)
        try:
            course = Course.objects.get(name=c)
            student = Student.objects.get(name=s)
        except ObjectDoesNotExist:
            return HttpResponseRedirect(reverse('management:assign_course'))
        try:
            match = course.its_students.all()
        except Course.DoesNotExist:
            return HttpResponseRedirect(reverse('management:assign_course'))
        if student in match :
            return HttpResponseRedirect(reverse('management:assign_course'))
        else:
            student.courses.add(course)
            course.increase_student()
            course.save()
            return render(request, "management/assign_course.html",{
                "message":f"Assigned {course} to {student}"
            })
    return HttpResponseRedirect(reverse('management:index'))

@login_required(login_url='login:login')
def add_teacher(request):
    choices = []
    try:
        departments = Department.objects.all()
    except Department.DoesNotExist:
        return HttpResponseRedirect(reverse('management:departments'))
    for department in departments:
        s = (department.id, department.name)
        choices.append(s)
        return render(request, 'management/add_teacher.html', {
        "form": Teacher_form(),
        "message": None
    })

def save_teacher(request):
    if request.method == 'POST':
        form = Teacher_form(request.POST,request.FILES)
        if form.is_valid():
            first_name = form.cleaned_data['first_name'].capitalize()
            last_name = form.cleaned_data['last_name'].capitalize()
            name = first_name + " " + last_name
            department_id = form.cleaned_data['department']
            gender = form.cleaned_data['gender']
            age = form.cleaned_data['age']
            department = Department.objects.get(pk=department_id)
            pro_pic = form.cleaned_data['pro_pic']
            dept_id = form.cleaned_data['head'][0]
            head = Department.objects.get(pk=dept_id)
            try:
                teacher = Teacher.objects.get(name=name)
                return render(request, 'management/add_teacher.html', {
                    "form":form,
                    "message": "Teacher already registered!"
                })
            except:
                teacher = Teacher(name=name,department=department,gender=gender,age=age,pro_pic=pro_pic,head=head)
                teacher.save()
                return HttpResponseRedirect(reverse('management:add_teacher'))
        else:
            return render(request, 'management/add_teacher.html', {
                "form":form,
                "message":"Form is not valid!"
            })

    return HttpResponseRedirect(reverse("management:add_teacher"))

def list_teachers(request):
    try:
        teachers = Teacher.objects.all()

    except Teacher.EmptyResultSet:
        return render(request, "management/teachers.html")

    return render(request, "management/teachers.html", {
        "teachers": teachers,
        "form": Upload_form()
    })
@login_required(login_url='login:login')
def upload_pic(request):
    if request.method == "POST":
        form = Upload_form(request.POST,request.FILES)

        if form.is_valid():
            pic = form.cleaned_data['pro_pic']
            name = request.POST['name']
            teacher = Teacher.objects.get(name = name)
            teacher.pro_pic = pic
            teacher.save()
            return HttpResponseRedirect(reverse('management:list_teachers'))

        else:
            return HttpResponseRedirect(reverse('management:list_teachers'))
    else:
        return HttpResponseRedirect(reverse('management:list_teachers'))

def departments(request):
    try:
        departments = Department.objects.all()
    except EmptyResultSet:
        return HttpResponse('No Departments found!')
    return render(request, 'management/departments.html', {
        "departments": departments
    })

def courses(request, department):
    try:
        dep = Department.objects.get(name=department.capitalize())
    except Department.DoesNotExist:
        return HttpResponseRedirect(reverse('management:departments'))
    courses = dep.its_courses.all()
    return render(request, "management/courses.html", {
        "courses":courses,
        "department":department
    })
def course_details(request,department,course):
    try:
        course_details = Course.objects.get(name = course)
    except Course.DoesNotExist:
        return HttpResponse("Course not found!")
    return render(request, "management/course_details.html",{
        "course_details": course_details,
        "students": course_details.its_students.all()
    })

management/templates/management/add_student.html
{% extends "management/layout.html" %}

{% block title %}
    Add Student
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-lg-3">

        </div>
        <div class="col-lg-6 border border-white rounded mx p-4" style="background-color:#05F1B8;">
            <h3 class="">Register New Student</h3>

            <form action="{% url 'management:save_student' %}" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <p>
                {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{request.GET.next}}">
                {% endif %}
            </p>
            
                <input class="btn btn-sm btn-success" type="submit">
                
            </form>
            <br>
            {% if message %}
                {{message}}
            {% endif %}
            <br>
        </div>
        <div class="col-lg-3">

        </div>
    </div>
    
{% endblock %}

management/templates/management/add_teacher.html
{% extends "management/layout.html" %}

{% block title %}
    Add Teacher
{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-lg-3">


        </div>
        <div class="col-lg-6 border border-white rounded mx p-4" style="background-color:#05F1B8;">
            <h3 class="">Register New Teacher</h3>

            <form action="{% url 'management:save_teacher' %}" enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <p>
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{request.GET.next}}">
                    {% endif %}
                </p>
            
                <input class="btn btn-sm btn-success" type="submit">
                
            </form>
            <br>
        </div>
        <div class="col-lg-3">
            {% if message %}
            
            <div class="alert alert-primary text-center" role="alert">
                {{message}}
              </div>
                
            {% endif %}
        </div>
    </div>
    
{% endblock %}

management/templates/management/assign_course.html
{% extends "management/layout.html" %}
{% load static %}
{% block title %}
    Assign Course
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-lg-3">
        <img src="{% static 'management/assign_course.png' %}" alt="assign_course" style="width: 250px;" class="">
    </div>
    <div class="col-lg-6 border border-white rounded mx p-4" style="background-color:#05F1B8;">
        <h3 class="">Assign Course to Student</h3>
        <form action="{% url 'management:save_to_course' %}", method="POST">
            {% csrf_token %}

            <div class="form-group">
                <label for="exampleFormControlSelect1">Available Courses from the dropdown</label>
                <select name="course" class="form-control form-control-sm" id="exampleFormControlSelect1">
                    {% for course in courses %}
                        <option value="{{course.name}}">{{course}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="a">Students List</label>
                <select name="student" class="form-control form-control-sm" id="a">
                    {% for student in students %}
                        <option value="{{student.name}}">{{student}}</option>
                    {% endfor %}
                </select>
            </div>
            <p>
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{request.GET.next}}">
            
            {% endif %}
            </p>
            
            <input class="btn btn-sm btn-success" type="submit">
        
        </form>
        <br>
        {% if message %}
            {{message}}
        {% endif %}
    </div>
    <div class="col-lg-3">

    </div>
</div>
    {% endblock %}

management/templates/management/course_details.html
{% extends "management/layout.html" %}
{% load static %}

{% block title %}
    {{course|title}} Details
{% endblock %}

{% block body %}
<h3 class="text-center">{{course|title}} Related Informations</h3>
    <div class="row">
        <div class="col-lg-3">

        </div>
        <div class="col-lg-6">
            <table class="table table-sm">
                <thead>
                  <tr>
                    <th scope="col">Course Name</th>
                    <th scope="col">Capacity</th>
                    <th scope="col">Enrolled</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">{{course_details.name}}</th>
                    <td>10</td>
                    <td>{{course_details.capacity}}</td>
                  </tr>
                </tbody>
              </table>
              
              {% if request.user.id %}
              <h3 class="text-center">Enrolled Students</h3>
                <table class="table table-sm">
                  <thead>
                    <tr>
                      <th scope="col">Student ID</th>
                      <th scope="col">Name</th>
                      <th scope="col">Gender</th>
                    </tr>
                  </thead>
                  <tbody>
                      {% for student in students %}
                          <tr>
                          
                              <th scope="row">{{student.id}}</th>
                              <td>{{student.name}}</td>
                              <td>{{student.gender|title}}</td>
                          
                          </tr>
                      {% empty %}
                          <li>No student enrolled!</li>
                      {% endfor %}
                  </tbody>
                </table>
              {% endif %}
        </div>
        <div class="col-lg-3">

        </div>
    </div>
    
{% endblock %}

management/templates/management/courses.html
{% extends "management/layout.html" %}
{% load static %}

{% block title %}
    Departments
{% endblock %}

{% block body %}
<h3 class="text-center">{{department|title}} Department offered Courses</h3>
    <div class="row">
        <div class="col-lg-3">

        </div>
        <div class="col-lg-6">
            <h5>List</h5>
            {% for course in courses %}
                <ul>
                    <li value="{{course.name}}"><a href="{% url 'management:course_details' department course.name %}">{{course}}</a></li>
                </ul>
            {% empty %}
                <ul>
                    <li>No course offered</li>
                </ul>
            {% endfor %}
        </div>
        <div class="col-lg-3">

        </div>
    </div>
    
{% endblock %}

management/templates/management/departments.html
{% extends "management/layout.html" %}
{% load static %}

{% block title %}
    Departments
{% endblock %}

{% block body %}
<h3 class="text-center">All Departments</h3>
    <div class="row">
        <div class="col-lg-3">

        </div>
        <div class="col-lg-6">
          <table class="table table-sm">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Department Name</th>
                <th scope="col">Department Head</th>
              </tr>
            </thead>
            <tbody>
              {% for department in departments %}
                <tr>
                  <th scope="row">{{department.id}}</th>
                  <td><a href="{% url 'management:courses' department %}">{{department.name}}</a></td>
                  {% if department.department_head.get %}
                    <td>{{department.department_head.get}}</td>
                  {% else %}
                    <td>N/A</td>
                  {% endif %}
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="col-lg-3">

        </div>
    </div>
    
{% endblock %}

management/templates/management/index.html
{% extends "management/layout.html" %}
{% block title %}
Home
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-lg-3">

        </div>
        <div class="col-lg-6 border border-white rounded mx p-4" style="background-color:#05F1B8;">
            <h3>Register New Course</h3>
            <form action="{% url 'management:save_course' %}" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn-sm btn-success" type="submit">
            </form>
            <br>
            {% if message %}
                {{message}}
            {% endif %}
        </div>

        <div class="col-lg-3">
        </div>
        
    </div>

{% endblock %}

management/templates/management/layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'management/styles.css' %}">
        <title>
            {% block title %}
            {% endblock %}
        </title>
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Pathway+Gothic+One&display=swap" rel="stylesheet">
    </head>
    <body class="">
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'management:home' %}">
                <img src="{% static 'management/logo.png' %}" width="30" height="30" alt=""> 
              </a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link " href="{% url 'management:list_teachers' %}" tabindex="-1" aria-disabled="true">Available Teachers</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'management:departments' %}">Departments</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'management:add_student' %}">Enroll</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link " href="{% url 'management:assign_course' %}" tabindex="-1" aria-disabled="true">Assign Course</a>
                  </li>
                  
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'management:add_course' %}">Add Course</a>
                      <a class="dropdown-item" href="{% url 'management:add_teacher' %}">Appoint New Teacher</a>
                    </div>
                  </li>
                </ul>
                <div class="d-flex">
                  {% if request.user.id %}
                    <a class="btn btn-sm btn-success" role="button" href="{% url 'login:logout' %}">Logout {{request.user|title}}</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </nav>
        <div class="container mt-5">
            {% block body %}
              
            {% endblock %}
            
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

management/templates/management/teachers.html
{% extends 'management/layout.html' %}
{% load static %}

{% block title %}
    Teachers
{% endblock %}

{% block body %}

<h3 class="text-center">All Teachers</h3>
<div class="row">
    {% for teacher in teachers %}
    <div class="col-lg-3 border border-white rounded mx p-4" style="background-color:#05F1B8;">
        {% if teacher.pro_pic %}
            <img class="img-thumbnail" src="{{ teacher.pro_pic.url }}" alt="Profile picture of {{teacher.name}}">
        {% else %}
            {% if teacher.gender == "male" %}
                <img src="{% static 'management/male.png' %}" class="img-thumbnail" alt="">
                <br>
                {% if request.user.id %}
                    <form action="{% url 'management:upload_pic' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <input type="hidden" name="name", value="{{teacher.name}}">
                        <input type="submit" value="upload">
                    </form>
                {% endif %}
            {% elif teacher.gender == "female" %}
                <img src="{% static 'management/female.png' %}" class="img-thumbnail" alt="">
                <br>
                {% if request.user.id %}
                    <form action="{% url 'management:upload_pic' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <input type="hidden" name="name", value="{{teacher.name}}">
                        <input type="submit" class="btn btn-success" value="Upload">
                    </form>
                {% endif %}
            {% else %}
                <img src="{% static 'management/transgender.jpg' %}" class="img-thumbnail" alt="">
                <br>
                {% if request.user.id %}
                    <form action="{% url 'management:upload_pic' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.as_p}}
                        <input type="hidden" name="name", value="{{teacher.name}}">
                        <input type="submit" class="btn btn-success" value="Upload">
                    </form>
                {% endif %}
            {% endif %}

        {% endif %}
    </div>
    <div class="col-lg-6 border border-white rounded mx p-4" style="background-color:#4DF9DA;">
        <p><strong>Name:</strong> {{teacher.name}}</p>
        <p><strong>Department:</strong> {{teacher.department}}</p> 
        <p><strong>Gender:</strong> {{teacher.gender|title}}</p> 
        <p><strong>Age:</strong> {{teacher.age}}</p>
        {% if teacher.head %}
            <p>Head of <strong><a href="{% url 'management:courses' teacher.head %}">{{teacher.head}}</a></strong> Department</p>
        {% endif %}
    

    </div>
    <div class="col-lg-3">
        
            
    </div>

    
    {% empty %}
        <p><strong>Message:</strong> No registered teacher found! </p>
    {% endfor %}
</div>
{% endblock %}